# -*- coding: utf-8 -*-

CONSUMER_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXX'                               # Consumer Key
CONSUMER_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'   # Consumer Secret
ACCESS_TOKEN = 'XXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'      # Access Token
ACCESS_TOKEN_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'    # Accesss Token Secert
